# .github/workflows/deno.yml
name: Deno CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [main]

jobs:
  deno-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Create coverage directory
        run: mkdir -p coverage

      - name: Check formatting
        working-directory: .
        run: deno fmt --check

      - name: Check types
        working-directory: .
        run: deno check

      - name: Test code
        working-directory: .
        run: |
          deno test --coverage=cov_backend -A --parallel
          deno coverage cov_backend --lcov --output=coverage/backend.lcov

      - name: Lint code
        working-directory: .
        run: deno lint

      - name: Setup LCOV
        if: github.event_name == 'pull_request'
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Report LCOV
        uses: zgosalvez/github-actions-report-lcov@v4
        if: github.event_name == 'pull_request'
        with:
          coverage-files: |
            coverage/backend.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
          artifact-name: code-coverage-report

      - name: Cleanup coverage dirs
        run: rm -rf cov_backend
