# .github/workflows/deno.yml
name: Deno CI

on:
  push:
    branches: ["**"]

jobs:
  deno-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Init backend
        working-directory: ./backend
        run: deno install

      - name: Check backend formatting
        working-directory: ./backend
        run: deno fmt --check

      - name: Check backend types
        working-directory: ./backend
        run: deno check

      - name: Test backend code
        working-directory: ./backend
        run: deno test -A

      - name: Init frontend
        working-directory: ./frontend
        run: deno install

      - name: Check frontend formatting
        working-directory: ./frontend
        run: deno fmt --check

      - name: Check frontend types
        working-directory: ./frontend
        run: deno check

      - name: Test frontend code
        working-directory: ./frontend
        run: deno test -A
